stages:
  - build
  #- deploy

variables:
  HUBOT_NATURAL_RELEASE_IMAGE: $CI_REGISTRY_IMAGE/hubot_natural:$CI_BUILD_REF_NAME

build hubot_natural:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build -f Dockerfile -t $HUBOT_NATURAL_RELEASE_IMAGE .
    - docker tag $HUBOT_NATURAL_RELEASE_IMAGE "$CI_REGISTRY_IMAGE/hubot_natural:latest"
    - docker push $HUBOT_NATURAL_RELEASE_IMAGE
    - docker push "$CI_REGISTRY_IMAGE/hubot_natural:latest"
  only:
    - /master|develop|gitlab-ci-test/
  environment: development
  tags:
    - docker

#deploy:
#  image: cdrx/rancher-gitlab-deploy
#  stage: deploy
#  services:
#    - docker:dind
#  script:
#    - upgrade --environment Development --stack Rouana --service hubot-natural --new-image $HUBOT_NATURAL_RELEASE_IMAGE --no-finish-upgrade --debug
#  only:
#    - /master|develop/
#  environment: development
#  tags:
#    - docker
