stages:
  - build
  - deploy_to_development
  - deploy_to_production

variables:
  ROUANA_RELEASE_IMAGE: $CI_REGISTRY_IMAGE/rouana:$CI_BUILD_REF_NAME

build rouana:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build -f Dockerfile -t $ROUANA_RELEASE_IMAGE .
    - docker tag $ROUANA_RELEASE_IMAGE "$CI_REGISTRY_IMAGE/rouana:latest"
    - docker push $ROUANA_RELEASE_IMAGE
    - docker push "$CI_REGISTRY_IMAGE/rouana:latest"
  only:
    - /master|develop/
  environment: development
  tags:
    - docker

deploy_to_development:
  image: cdrx/rancher-gitlab-deploy
  stage: deploy_to_development
  services:
    - docker:dind
  script:
    - upgrade --environment Development --stack RouanaBot --service rouana --new-image $ROUANA_RELEASE_IMAGE --no-finish-upgrade --debug
  only:
    - /develop/
  environment: development
  tags:
    - docker

deploy_to_production:
  image: cdrx/rancher-gitlab-deploy
  stage: deploy_to_production
  services:
    - docker:dind
  script:
    - upgrade --environment Production --stack RouanaBot --service rouana --new-image $ROUANA_RELEASE_IMAGE --no-finish-upgrade --debug
  only:
    - /master/
  environment: production
  tags:
    - docker
