stages:
  - build
  - deploy

variables:
  TAIS_LATEST_IMAGE: $CI_REGISTRY_IMAGE/tais:latest
  LANDING_PAGE_LATEST_IMAGE: $CI_REGISTRY_IMAGE/landing_page:latest

build tais:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build -f docker/tais/rocketchat.Dockerfile -t $TAIS_LATEST_IMAGE .
    - docker push $TAIS_LATEST_IMAGE
    - docker push "$CI_REGISTRY_IMAGE/tais:latest"
    - docker build -f docker/landing_page/Dockerfile -t $LANDING_PAGE_LATEST_IMAGE .
    - docker push $LANDING_PAGE_LATEST_IMAGE
    - docker push "$CI_REGISTRY_IMAGE/landing_page:latest"
  only:
    - /master|test_ci/
  environment: development
  tags:
    - docker

deploy_to_development:
  image: cdrx/rancher-gitlab-deploy
  stage: deploy
  services:
    - docker:dind
  script:
    - upgrade --environment Development --stack TAIS --service tais --new-image $TAIS_LATEST_IMAGE --no-finish-upgrade --debug
    - upgrade --environment Development --stack TAIS --service landing-page --new-image $LANDING_PAGE_LATEST_IMAGE --no-finish-upgrade --debug
  only:
    - /master|test_ci/
  environment: development
  tags:
    - docker

deploy_to_production:
  image: cdrx/rancher-gitlab-deploy
  stage: deploy
  services:
    - docker:dind
  script:
    - upgrade --environment Production --stack TAIS --service tais --new-image $TAIS_LATEST_IMAGE --no-finish-upgrade --debug
    - upgrade --environment Production --stack TAIS --service landing-page --new-image $LANDING_PAGE_LATEST_IMAGE --no-finish-upgrade --debug
  only:
    - tags
  environment: production
  tags:
    - docker
