version: '2'

services:
  rocketchat:
    image: rocket.chat:0.68.3
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - ADMIN_USERNAME=admin
      - ADMIN_PASS=admin
    depends_on:
      - mongo
    ports:
      - 3000:3000

  mongo:
    image: mongo:3.2
    restart: unless-stopped
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles --oplogSize 128

  rouana:
    build:
      context: .
      dockerfile: ./docker/tais/Dockerfile
    environment:
      - TRAINING_EPOCHS=300
      - CREDENTIALS=/rouana/credentials.yml
      - ROCKETCHAT_URL=http://rocketchat:3000
    volumes:
      - ./rouana:/rouana
      - ./scripts:/scripts
    depends_on:
      - rocketchat

  landing-page:
    build:
      context: .
      dockerfile: ./docker/landing_page/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./landing_page/nginx/htpasswd:/etc/nginx/.htpasswd
  
