# policies:
#   - name: KerasPolicy
#     epochs: TRAINING_EPOCHS
#     featurizer:
#       - name: FullDialogueTrackerFeaturizer
#       state_featurizer:
#         - name: LabelTokenizerSingleStateFeaturizer
#   - name: FallbackPolicy
#       nlu_threshold: NLU_THRESHOLD
#       core_threshold: CORE_THRESHOLD
#   - name: MemoizationPolicy
#       max_history: MAX_HISTORY
#       USE_NLU_CONFIDENCE_AS_SCORE: True

policies:
  - name: KerasPolicy
    epochs: 200
    batch_size: 50
    max_training_samples: 300
  - name: FallbackPolicy
  - name: MemoizationPolicy